export const GET_INDEX_LIST = '/api/index.json?city='
export const GET_NEAR_LIST = '/api/near.json'
export const GET_PLAY_LIST = '/api/play.json?type='
export const GET_PUNCH_LIST = '/api/punch.json'
export const GET_TRAVELING_LIST = '/api/traveling.json'
export const GET_DETAIL_INFO = '/api/detail.json'
export const GET_STRAGEGY_COMMENT = '/api/stragegyAndComment.json'
export const GET_FUSION_LIST = '/api/fusion.json'
